### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by KMFrench1** [CyborgCabbage/universebox#1]
Not sure what cashes it, but when I install you mod, my game crashes. Here is the log.
[crash-2022-02-05_03.32.01-server.txt](https://github.com/CyborgCabbage/universebox/files/8007659/crash-2022-02-05_03.32.01-server.txt)
.

**Comment by KMFrench1** [comment]
[latest.log](https://github.com/CyborgCabbage/universebox/files/8007660/latest.log)
Also the full log.

**Comment by CyborgCabbage** [comment]
After testing it, this crash is caused by AdventureZ and Unlimited Dragon Eggs. It occurs whether my mod is present or not.
