### ISSUE TITLE
Version availability issues

### ISSUE THREAD

**Issue by SylisMC** [CyborgCabbage/universebox#3]
Just incase you arent aware, 
the latest version of immersive portals available on curse forge for 1.19.2 is 2.2.5 (Your mod required 2.3.0)
So anyone downloading your mod via the curse launcher will automatically crash due to version availability issues.

Immersive Portals Links
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) [Modrinth](https://modrinth.com/mod/immersiveportals)

**Full Error**
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals Core' (imm_ptl_core) 2.2.5 with version 2.3.0 or later.
Unmet dependency listing:
	 - Mod 'Universe Box' (universebox) 1.2.0+mc1.19.2 requires version 2.3.0 or later of mod 'Immersive Portals Core' (imm_ptl_core), but only the wrong version is present: 2.2.5!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by CyborgCabbage** [comment]
There is a bug with 2.2.5 so the mod only works with 2.3.0+. This issue should resolve itself, the mod creator probably just forgot to upload to Curseforge.
