### ISSUE TITLE
Insta-crash when opening a box below Y=0 or above Y=255

### ISSUE THREAD

**Issue by DarianLStephens** [CyborgCabbage/universebox#6]
The moment you try to open a Universe Box that's placed below Y=0, the game will crash. It looks like it's trying to read data from a block that doesn't exist?
Crash log: [https://pastebin.com/35eWDr45](https://pastebin.com/35eWDr45)

Placing above Y=0 is fine:
![2023-01-14_16 28 06](https://user-images.githubusercontent.com/15375876/212457560-a7fe3892-673e-43b2-bc6d-60bef1cbf668.png)
Opening is, too:
![2023-01-14_16 28 09](https://user-images.githubusercontent.com/15375876/212457561-b3ef2cd2-c10a-4271-a1f6-f736bca71d41.png)

Placing below Y=0 is okay, but the game crashes the moment you try to open it.
![2023-01-14_16 28 27](https://user-images.githubusercontent.com/15375876/212457569-3997ddf3-bd02-4314-9746-7dc2f163cdd0.png)

**Comment by DarianLStephens** [comment]
The game also crashes every time you try to open the world after doing this, with what appears to be the same error.

**Comment by DarianLStephens** [comment]
I've just discovered that the same thing happens when opening it above Y=255, so it's whatever bounds are in the box dimension.

**Comment by DarianLStephens** [comment]
I tried fixing it by increasing the size of the box dimension to match the overworld, but it then started crashing _inside_ the previously-okay range.

**Comment by Danksukii** [comment]
I have encountered this issue too. I hope a fix comes soon, as I'd love to have this mod on my server.

**Comment by Nitjsefnie** [comment]
Damn, took a few hours and my sanity, but I've found the issue:
https://github.com/CyborgCabbage/universebox/blob/master/src/main/java/cyborgcabbage/universebox/portal/DependentPortal.java#L62
https://github.com/CyborgCabbage/universebox/blob/master/src/main/java/cyborgcabbage/universebox/portal/DependentPortal.java#L63
world -> parentWorld fixes it. 
@Danksukii @DarianLStephens if you can, you can clone, fix it and compile or hit me up on Discord (it's in my GitHub profile)

**Comment by Nitjsefnie** [comment]
The thing that this mod worked at all was just a pure coincidence
